[pytest]
testpaths = tests
python_files = test_*.py
markers =
    smoke: pruebas críticas del flujo principal
    login: pruebas relacionadas al inicio de sesión
    catalogo: pruebas relacionadas con el catálogo de productos
    carrito: pruebas relacionadas con el carrito de compras