[pytest]
testpaths =
    tests
    tests_api

addopts = -v --html=reports/report.html --self-contained-html

markers =
    login: pruebas relacionadas con el inicio de sesión
    catalogo: pruebas relacionadas con el catálogo de productos
    carrito: pruebas relacionadas con el carrito de compras
    checkout: pruebas relacionadas con el flujo de compra
    api: pruebas automatizadas de API con requests